export type ScreenStatus = "IMPLEMENTED" | "ADAPTED_TO_CHUDO" | "DEFERRED" | "NOT_APPLICABLE_OWNER_APPROVAL_REQUIRED";

export type ImplementationKind = "DEDICATED_SCREEN" | "SHARED_SEMANTIC_SCREEN" | "RUNTIME_STATE" | "COVERAGE_PLACEHOLDER";

export type ScreenImplementationDescriptor = {
  screenId: string;
  route: string;
  implementationKind: ImplementationKind;
  componentKey: string;
  semanticKey: string;
  interactionKey: string;
  publicReady: boolean;
  status: ScreenStatus;
};

/**
 * Append-only runtime renderer contract.
 *
 * Every canonical target owns a complete descriptor. There is deliberately no
 * family fallback, implicit IMPLEMENTED status, or inferred publicReady value.
 * The router consumes componentKey and SemanticRouteScreen consumes semanticKey,
 * so these declarations select the real renderer instead of merely describing it.
 */
export const screenImplementationRegistry: readonly ScreenImplementationDescriptor[] = [
  { screenId: "01.01", route: "/splash", implementationKind: "DEDICATED_SCREEN", componentKey: "OnboardingScreen", semanticKey: "splash", interactionKey: "splash:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "01.02", route: "/welcome", implementationKind: "DEDICATED_SCREEN", componentKey: "OnboardingScreen", semanticKey: "welcome", interactionKey: "welcome:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "01.03", route: "/access/create-account", implementationKind: "DEDICATED_SCREEN", componentKey: "OnboardingScreen", semanticKey: "access-create-account", interactionKey: "access-create-account:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "01.04", route: "/access/recovery", implementationKind: "DEDICATED_SCREEN", componentKey: "OnboardingScreen", semanticKey: "access-recovery", interactionKey: "access-recovery:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "01.05", route: "/access/create-pin", implementationKind: "DEDICATED_SCREEN", componentKey: "OnboardingScreen", semanticKey: "access-create-pin", interactionKey: "access-create-pin:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "01.06", route: "/access/enter-pin", implementationKind: "DEDICATED_SCREEN", componentKey: "OnboardingScreen", semanticKey: "access-enter-pin", interactionKey: "access-enter-pin:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "01.07", route: "/access/permissions", implementationKind: "DEDICATED_SCREEN", componentKey: "OnboardingScreen", semanticKey: "access-permissions", interactionKey: "access-permissions:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "02.01", route: "/home", implementationKind: "DEDICATED_SCREEN", componentKey: "ProductHomeScreen", semanticKey: "home", interactionKey: "home:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "02.02", route: "/home/promo", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "HomeSemantic", semanticKey: "home-promo", interactionKey: "home-promo:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "02.03", route: "/home/quick-actions", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "HomeSemantic", semanticKey: "home-quick-actions", interactionKey: "home-quick-actions:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "02.04", route: "/home/favorites", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "HomeSemantic", semanticKey: "home-favorites", interactionKey: "home-favorites:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "02.05", route: "/home/favorites-empty", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "HomeSemantic", semanticKey: "home-favorites-empty", interactionKey: "home-favorites-empty:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "02.06", route: "/home/notification-entry", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "HomeSemantic", semanticKey: "home-notification-entry", interactionKey: "home-notification-entry:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.01", route: "/chats", implementationKind: "DEDICATED_SCREEN", componentKey: "ChatsScreen", semanticKey: "chats", interactionKey: "chats:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.02", route: "/chats/search", implementationKind: "DEDICATED_SCREEN", componentKey: "ChatsScreen", semanticKey: "chats-search", interactionKey: "chats-search:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.03", route: "/chats/filters", implementationKind: "DEDICATED_SCREEN", componentKey: "ChatsScreen", semanticKey: "chats-filters", interactionKey: "chats-filters:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.04", route: "/chats/yuri", implementationKind: "DEDICATED_SCREEN", componentKey: "ChatsScreen", semanticKey: "chats-yuri", interactionKey: "chats-yuri:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.05", route: "/chats/yuri/attachments", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "ChatSemantic", semanticKey: "chats-yuri-attachments", interactionKey: "chats-yuri-attachments:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.06", route: "/chats/yuri/attachment-preview", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "ChatSemantic", semanticKey: "chats-yuri-attachment-preview", interactionKey: "chats-yuri-attachment-preview:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.07", route: "/chats/yuri/payment", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "ChatSemantic", semanticKey: "chats-yuri-payment", interactionKey: "chats-yuri-payment:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.08", route: "/calls/audio", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-audio", interactionKey: "calls-audio:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.09", route: "/calls/video", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-video", interactionKey: "calls-video:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.10", route: "/calls/incoming", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-incoming", interactionKey: "calls-incoming:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.11", route: "/calls/outgoing", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-outgoing", interactionKey: "calls-outgoing:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.12", route: "/calls/ringing", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-ringing", interactionKey: "calls-ringing:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.13", route: "/calls/connecting", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-connecting", interactionKey: "calls-connecting:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.14", route: "/calls/connected", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-connected", interactionKey: "calls-connected:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.15", route: "/calls/reconnecting", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-reconnecting", interactionKey: "calls-reconnecting:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.16", route: "/calls/failed", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-failed", interactionKey: "calls-failed:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.17", route: "/calls/ended", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-ended", interactionKey: "calls-ended:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.18", route: "/calls/minimized", implementationKind: "RUNTIME_STATE", componentKey: "CallOverlay", semanticKey: "calls-minimized", interactionKey: "calls-minimized:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "03.19", route: "/calls", implementationKind: "DEDICATED_SCREEN", componentKey: "CallsScreen", semanticKey: "calls", interactionKey: "calls:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.01", route: "/wallet", implementationKind: "DEDICATED_SCREEN", componentKey: "ProductWalletScreen", semanticKey: "wallet", interactionKey: "wallet:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.02", route: "/wallet/balance", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-balance", interactionKey: "wallet-balance:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.03", route: "/wallet/assets", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-assets", interactionKey: "wallet-assets:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.04", route: "/wallet/chudo", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-chudo", interactionKey: "wallet-chudo:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.05", route: "/wallet/chudo/chart", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-chudo-chart", interactionKey: "wallet-chudo-chart:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.06", route: "/wallet/transactions", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-transactions", interactionKey: "wallet-transactions:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.07", route: "/wallet/transaction/tx-received-128", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-transaction-tx-received-128", interactionKey: "wallet-transaction-tx-received-128:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.08", route: "/wallet/send", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-send", interactionKey: "wallet-send:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.09", route: "/wallet/send/validation", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-send-validation", interactionKey: "wallet-send-validation:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.10", route: "/wallet/send/review", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-send-review", interactionKey: "wallet-send-review:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.11", route: "/wallet/send/confirmation", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-send-confirmation", interactionKey: "wallet-send-confirmation:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.12", route: "/wallet/send/receipt", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-send-receipt", interactionKey: "wallet-send-receipt:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.13", route: "/wallet/receive", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-receive", interactionKey: "wallet-receive:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.14", route: "/wallet/receive/qr", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-receive-qr", interactionKey: "wallet-receive-qr:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.15", route: "/wallet/scan", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-scan", interactionKey: "wallet-scan:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "04.16", route: "/wallet/send/recipient", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "WalletRouteScreen", semanticKey: "wallet-send-recipient", interactionKey: "wallet-send-recipient:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.01", route: "/market", implementationKind: "DEDICATED_SCREEN", componentKey: "MarketScreen", semanticKey: "market", interactionKey: "market:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.02", route: "/market/search", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-search", interactionKey: "market-search:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.03", route: "/market/filters", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-filters", interactionKey: "market-filters:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.04", route: "/market/chudo-eur", implementationKind: "DEDICATED_SCREEN", componentKey: "MarketScreen", semanticKey: "market-chudo-eur", interactionKey: "market-chudo-eur:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.05", route: "/market/chudo-btc", implementationKind: "DEDICATED_SCREEN", componentKey: "MarketScreen", semanticKey: "market-chudo-btc", interactionKey: "market-chudo-btc:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.06", route: "/market/chudo-usdt", implementationKind: "DEDICATED_SCREEN", componentKey: "MarketScreen", semanticKey: "market-chudo-usdt", interactionKey: "market-chudo-usdt:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.07", route: "/market/chudo-eur/detail", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-detail", interactionKey: "market-chudo-eur-detail:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.08", route: "/market/chudo-eur/chart", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-chart", interactionKey: "market-chudo-eur-chart:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.09", route: "/market/chudo-eur/periods", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-periods", interactionKey: "market-chudo-eur-periods:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.10", route: "/market/chudo-eur/order-book", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-order-book", interactionKey: "market-chudo-eur-order-book:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.11", route: "/market/chudo-eur/trades", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-trades", interactionKey: "market-chudo-eur-trades:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.12", route: "/market/chudo-eur/buy", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-buy", interactionKey: "market-chudo-eur-buy:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.13", route: "/market/chudo-eur/sell", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-sell", interactionKey: "market-chudo-eur-sell:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.14", route: "/market/swap", implementationKind: "DEDICATED_SCREEN", componentKey: "SwapScreen", semanticKey: "market-swap", interactionKey: "market-swap:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.15", route: "/market/chudo-eur/review", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-review", interactionKey: "market-chudo-eur-review:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.16", route: "/market/chudo-eur/confirmation", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-confirmation", interactionKey: "market-chudo-eur-confirmation:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.17", route: "/market/chudo-eur/receipt", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-chudo-eur-receipt", interactionKey: "market-chudo-eur-receipt:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.18", route: "/market/orders", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-orders", interactionKey: "market-orders:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.19", route: "/market/order/demo-eur-01", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-order-demo-eur-01", interactionKey: "market-order-demo-eur-01:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.20", route: "/market/order/demo-eur-01/cancel", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-order-demo-eur-01-cancel", interactionKey: "market-order-demo-eur-01-cancel:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.21", route: "/market/history", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-history", interactionKey: "market-history:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "05.22", route: "/market/history/demo-trade-01", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MarketSemantic", semanticKey: "market-history-demo-trade-01", interactionKey: "market-history-demo-trade-01:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "06.01", route: "/portfolio", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "PortfolioSemantic", semanticKey: "portfolio", interactionKey: "portfolio:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "06.02", route: "/portfolio/value", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "PortfolioSemantic", semanticKey: "portfolio-value", interactionKey: "portfolio-value:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "06.03", route: "/portfolio/allocation", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "PortfolioSemantic", semanticKey: "portfolio-allocation", interactionKey: "portfolio-allocation:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "06.04", route: "/portfolio/performance", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "PortfolioSemantic", semanticKey: "portfolio-performance", interactionKey: "portfolio-performance:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "06.05", route: "/portfolio/performance/periods", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "PortfolioSemantic", semanticKey: "portfolio-performance-periods", interactionKey: "portfolio-performance-periods:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "06.06", route: "/portfolio/watchlist", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "PortfolioSemantic", semanticKey: "portfolio-watchlist", interactionKey: "portfolio-watchlist:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "06.07", route: "/portfolio/watchlist-empty", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "PortfolioSemantic", semanticKey: "portfolio-watchlist-empty", interactionKey: "portfolio-watchlist-empty:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "06.08", route: "/portfolio/chudo", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "PortfolioSemantic", semanticKey: "portfolio-chudo", interactionKey: "portfolio-chudo:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.01", route: "/mining", implementationKind: "DEDICATED_SCREEN", componentKey: "MiningScreen", semanticKey: "mining", interactionKey: "mining:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.02", route: "/mining/miner-status", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-miner-status", interactionKey: "mining-miner-status:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.03", route: "/mining/pool-status", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-pool-status", interactionKey: "mining-pool-status:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.04", route: "/mining/round", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-round", interactionKey: "mining-round:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.05", route: "/mining/workers", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-workers", interactionKey: "mining-workers:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.06", route: "/mining/earnings", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-earnings", interactionKey: "mining-earnings:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.07", route: "/mining/rewards", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-rewards", interactionKey: "mining-rewards:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.08", route: "/mining/reward/demo-round-48291", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-reward-demo-round-48291", interactionKey: "mining-reward-demo-round-48291:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.09", route: "/mining/connect", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-connect", interactionKey: "mining-connect:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.10", route: "/mining/settings", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-settings", interactionKey: "mining-settings:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "07.11", route: "/mining/no-miner", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "MiningSemantic", semanticKey: "mining-no-miner", interactionKey: "mining-no-miner:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.01", route: "/security", implementationKind: "DEDICATED_SCREEN", componentKey: "SecurityScreen", semanticKey: "security", interactionKey: "security:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.02", route: "/security/devices", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-devices", interactionKey: "security-devices:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.03", route: "/security/device/demo-phone", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-device-demo-phone", interactionKey: "security-device-demo-phone:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.04", route: "/security/sessions", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-sessions", interactionKey: "security-sessions:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.05", route: "/security/session/current", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-session-current", interactionKey: "security-session-current:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.06", route: "/security/backups", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-backups", interactionKey: "security-backups:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.07", route: "/security/backups-empty", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-backups-empty", interactionKey: "security-backups-empty:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.08", route: "/security/recovery", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-recovery", interactionKey: "security-recovery:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.09", route: "/security/confirmation", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-confirmation", interactionKey: "security-confirmation:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.10", route: "/security/trusted-contacts", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-trusted-contacts", interactionKey: "security-trusted-contacts:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.11", route: "/security/trusted-contact/yuri", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-trusted-contact-yuri", interactionKey: "security-trusted-contact-yuri:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.12", route: "/security/log", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-log", interactionKey: "security-log:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.13", route: "/security/pin", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-pin", interactionKey: "security-pin:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "08.14", route: "/security/unavailable", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SecuritySemantic", semanticKey: "security-unavailable", interactionKey: "security-unavailable:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.01", route: "/notifications", implementationKind: "DEDICATED_SCREEN", componentKey: "NotificationCenter", semanticKey: "notifications", interactionKey: "notifications:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.02", route: "/notifications/demo-notice", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "notifications-demo-notice", interactionKey: "notifications-demo-notice:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.03", route: "/documents", implementationKind: "DEDICATED_SCREEN", componentKey: "DocumentsScreen", semanticKey: "documents", interactionKey: "documents:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.04", route: "/documents/demo-overview", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "documents-demo-overview", interactionKey: "documents-demo-overview:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.05", route: "/documents/statements", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "documents-statements", interactionKey: "documents-statements:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.06", route: "/documents/statement/august", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "documents-statement-august", interactionKey: "documents-statement-august:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.07", route: "/documents/terms", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "documents-terms", interactionKey: "documents-terms:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.08", route: "/documents/privacy", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "documents-privacy", interactionKey: "documents-privacy:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.09", route: "/documents/security", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "documents-security", interactionKey: "documents-security:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.10", route: "/documents/legal", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "documents-legal", interactionKey: "documents-legal:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "09.11", route: "/documents/empty", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "DocumentSemantic", semanticKey: "documents-empty", interactionKey: "documents-empty:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.01", route: "/profile", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "profile", interactionKey: "profile:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.02", route: "/settings", implementationKind: "DEDICATED_SCREEN", componentKey: "SettingsScreen", semanticKey: "settings", interactionKey: "settings:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.03", route: "/settings/limits", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "settings-limits", interactionKey: "settings-limits:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.04", route: "/settings/language", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "settings-language", interactionKey: "settings-language:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.05", route: "/settings/appearance", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "settings-appearance", interactionKey: "settings-appearance:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.06", route: "/settings/notifications", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "settings-notifications", interactionKey: "settings-notifications:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.07", route: "/support/faq", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "support-faq", interactionKey: "support-faq:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.08", route: "/support", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "support", interactionKey: "support:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.09", route: "/settings/about", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "settings-about", interactionKey: "settings-about:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.10", route: "/settings/licenses", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "settings-licenses", interactionKey: "settings-licenses:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.11", route: "/settings/version", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "settings-version", interactionKey: "settings-version:local-demo", publicReady: true, status: "IMPLEMENTED" },
  { screenId: "10.12", route: "/settings/exit", implementationKind: "SHARED_SEMANTIC_SCREEN", componentKey: "SettingsSemantic", semanticKey: "settings-exit", interactionKey: "settings-exit:local-demo", publicReady: true, status: "IMPLEMENTED" },
];

export const screenImplementationById = new Map(
  screenImplementationRegistry.map(descriptor => [descriptor.screenId, descriptor] as const),
);

if (screenImplementationById.size !== screenImplementationRegistry.length) {
  throw new Error("Duplicate screenId in explicit implementation registry");
}
